New Challenge: K Closest Points to Origin, Algoritmos Avanzados: Lineales
PlatziLabs/playground-challenges pull request #173
Opened 2023-02-02 13:08 UTC by juandc

2023-02-10 16:56 UTC, nicobytes requested changes

2023-02-10 16:56 UTC, nicobytes commented on src/challenges/py/proalgoritmoslineales-06/src/main_test.py
> +def test_1_closest_point():
@juandc agrega un caso de prueba diferente al ejemplo

![image](https://user-images.githubusercontent.com/7611944/218150283-5a419665-10df-46fb-92bb-7bda3732201f.png)

2023-02-10 20:36 UTC, juandc commented on src/challenges/py/proalgoritmoslineales-06/src/main_test.py
> +def test_1_closest_point():
Agregados

2023-02-15 14:35 UTC, nicobytes approved these changes

2023-02-15 14:35 UTC, merged