Solution to Parenthesis, Algoritmos Avanzados: Lineales (post class)
PlatziLabs/playground-challenges pull request #176
Opened 2023-02-02 13:11 UTC by juandc

2023-02-15 16:01 UTC, nicobytes requested changes

2023-02-15 16:01 UTC, nicobytes commented on src/challenges/py/proalgoritmoslineales-05/src/main.py
> +   open = 0
@juandc open se reconoce como una función native de python y por ende se ve raro y no bueno sobreesribirla... mejor cambiar el nombre

<img width="344" alt="image" src="https://user-images.githubusercontent.com/7611944/219082064-f04a4a92-5b8d-43cc-bb96-bd379b178cc7.png">

2023-02-15 16:09 UTC, juandc commented on src/challenges/py/proalgoritmoslineales-05/src/main.py
> +   open = 0
Fixed!

2023-02-22 22:56 UTC, nicobytes approved these changes

2023-02-22 22:56 UTC, merged