New challenge: closure-sum for Curso de closures y Scope en Javascript
PlatziLabs/playground-challenges pull request #5
Opened 2022-10-20 22:17 UTC by LeoCode0

2022-10-21 02:55 UTC, nicobytes requested changes

2022-10-21 02:55 UTC, nicobytes commented on src/challenges/js/closure-sum/playground.json
> +  "title": "",
@LeoCode0 Aquí debes poner el titulo del ejercicio.

2022-10-21 02:55 UTC, nicobytes commented on src/challenges/js/closure-sum/src/exercise.test.js
> +  });
@LeoCode0 sería bueno agregar un caso de prueba con números negativos.

2022-10-21 02:55 UTC, nicobytes commented on src/challenges/js/count-words/src/exercise.js
> +  return array.flatMap(line => line.split(' ')).length;
@LeoCode0 por que modificar este ejercicio? en este caso debe quedar sin la solución.

2022-10-21 02:55 UTC, nicobytes commented on src/challenges/js/flat-array/src/exercise.js
> +  return array.flat();
@LeoCode0 por que modificar este ejercicio? en este caso debe quedar sin la solución.

2022-10-21 02:55 UTC, nicobytes commented on src/challenges/js/join-arrays/src/exercise.js
> +  return [...arrayA, ...arrayB];
@LeoCode0 por que modificar este ejercicio? en este caso debe quedar sin la solución.

2022-10-21 02:55 UTC, nicobytes commented on src/challenges/js/map-array/src/exercise.js
> +  return array.map(item => item.name);
@LeoCode0 por que modificar este ejercicio? en este caso debe quedar sin la solución.

2022-10-21 02:55 UTC, nicobytes commented on src/challenges/js/merge-json/src/exercise.js
> +export function solution(
@LeoCode0 por que modificar este ejercicio? en este caso debe quedar sin la solución.

2022-10-21 02:55 UTC, nicobytes commented on src/challenges/js/multiply-elements/src/exercise.js
> +  return array.map(item => item * 2);
@LeoCode0 por que modificar este ejercicio? en este caso debe quedar sin la solución.

2022-10-21 02:55 UTC, nicobytes commented on src/challenges/js/sort-desc-array/src/exercise.js
> +  return array.sort((a, b) => b - a);
@LeoCode0 por que modificar este ejercicio? en este caso debe quedar sin la solución.

2022-10-21 02:57 UTC, nicobytes commented
@LeoCode0 es un gran ejercicio solo arregla los comentarios que deje!

2022-10-21 16:42 UTC, LeoCode0 commented on src/challenges/js/closure-sum/src/exercise.test.js
> +  });
Agregado ✔️

2022-10-21 16:45 UTC, LeoCode0 commented on src/challenges/js/count-words/src/exercise.js
> +  return array.flatMap(line => line.split(' ')).length;
Al parecer se agregaron las soluciones cuando hice el sync del fork 🤔

Pero ya quite todas ✔️

2022-10-23 08:15 UTC, nicobytes approved these changes

2022-10-23 08:15 UTC, merged