New challenge: create-classes for Curso Básico de POO
PlatziLabs/playground-challenges pull request #8
Opened 2022-10-22 02:40 UTC by elyager

2022-10-23 08:26 UTC, nicobytes requested changes

2022-10-23 08:26 UTC, nicobytes commented on src/challenges/js/create-classes/src/exercise.test.js
> +  beforeEach(async () => {
@elyager aquí es necesario el async?

2022-10-23 08:26 UTC, nicobytes commented on src/challenges/js/create-classes/README.md
> +Dadas la siguientes clases:
@elyager colocar un "Enter" para que el md haga un salto de línea

2022-10-23 08:27 UTC, nicobytes commented
@elyager es un gran ejercicio y muy buenas pruebas unitarias 👏, te deje unos pequelños comentarios para arreglar.

2022-10-24 20:16 UTC, elyager commented on src/challenges/js/create-classes/src/exercise.test.js
> +  beforeEach(async () => {
🤔 not really

2022-10-24 21:16 UTC, nicobytes approved these changes

2022-10-24 21:16 UTC, merged